services:
  webapi:
    build:
      context: .
      dockerfile: src/UrlShortener.WebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      resources:
        reservations:
          cpus: "0.50"
          memory: 64M    
        limits:
          cpus: "1"
          memory: 128M