services:
  webapi:
    build:
      context: .
      dockerfile: src/UrlShortener.WebApi/Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 258M
          
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=YGonTxtRKV9cf83na6Pb0jI9qc4weJ
      - POSTGRES_DB=urlshortenerdb
      - MAX_CONNECTIONS=100
    ports:
      - "5432:5432"
    deploy:
      resources:
        reservations:
          cpus: "1.00"
          memory: 256M
        limits:
          cpus: "1.50"
          memory: 512M
          
  ngnix:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapi
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 64M
        limits:
          cpus: "0.25"
          memory: 128M
